version: '3'

tasks:
  check:
    cmds:
      - pyright src
      - ruff check src --fix --exit-non-zero-on-fix
    silent: true

  lint:
    cmds:
      - ruff check src --fix --exit-non-zero-on-fix
    silent: true
    
  fmt:
    cmds:
      - ruff format src
    silent: true