version: '3'

tasks:
  check:
    cmds:
      - pyright main.py
      - ruff check main.py --fix --exit-non-zero-on-fix
    silent: true

  lint:
    cmds:
      - ruff check main.py --fix --exit-non-zero-on-fix
    silent: true
    
  fmt:
    cmds:
      - ruff format main.py
    silent: true