name: Auto Approve

# on: pull_request_target

on:
  pull_request: 
    branches:
      - main

jobs:
  auto-approve:
    name: Auto Approve
    runs-on: ubuntu-24.04

    permissions:
      pull-requests: write

    # if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - name: Auto Approve
        uses: hmarr/auto-approve-action@v4
