name: Lint
on:
  push:
    branches: [main]
      
  pull_request:
    branches: [main]

jobs:
  Check:
    name: Check
    runs-on: ubuntu-24.04

    env:
      UV_CACHE_DIR: /tmp/.uv-cache

    steps:
      - name: Checkout Repository  
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Restore uv cache
        uses: actions/cache@v4
        with:
          path: /tmp/.uv-cache
          key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
            uv-${{ runner.os }}

      - name: Install dependencies
        run: | 
          uv sync --frozen

      - name: Check typing
        run: |
          uv run pyright src

      - name: Check codebase
        run: |
          uv run ruff check src --exit-non-zero-on-fix

      - name: Check for formatting
        run: |
          uv run ruff format src --check

      - name: Minimize uv cache
        run: |
          uv cache prune --ci
